services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Mapear porta 3000 do host para o contêiner
    environment:
      NODE_ENV: production
    restart: always
