export const units = [
  {
    municipio: "Arapiraca",
    uf: "AL",
    phone: "(82) 999227584",
    address: "Rua Lino Roberto, 692, Caititus",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower.alagoas",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Feira de Santana ",
    uf: "BA",
    phone: "(75) 9129-2331",
    address: "Home Office",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopower_fsabahia",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Salvador ",
    uf: "BA",
    phone: "(71) 996131300",
    address: "Av. Mário Leal Ferreira, 2230 - Loja 4 - Brotas",
    facebook: " -",
    instagram: "https://www.instagram.com/Ecopower_Salvador_Ba/",
    photo: "1REar8iTTWJaI3Qlzmar_0PlXp2KxvJlX.png",
  },
  {
    municipio: "Jequie",
    uf: "BA",
    phone: "(73) 988675702",
    address: "Rua 15 de Novembro 38, Centro",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopower_jequieba",
    photo: "1oZp1rQJ32Ss0bjp7VCsRAaHANQ_JWZ2x.png",
  },
  {
    municipio: "Vitória da Conquista ",
    uf: "BA",
    phone: "(77) 9 8136 5262",
    address: "Avenida Siqueira Campos, 323, Centro",
    facebook: "https://www.facebook.com/ecopowervca",
    instagram: "https://www.instagram.com/ecopowervcaa",
    photo: "1B3O0p1X1N2O1mUOyOJPWC6yXl2ssPMMx.png",
  },
  {
    municipio: "Valente",
    uf: "BA",
    phone: "(71) 98153-6043",
    address: "R. José Calixto, 318, Centro",
    facebook: "https://www.facebook.com/ecopowervalentebahia",
    instagram: "https://www.instagram.com/ecopower_valente",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Vila Velha",
    uf: "ES",
    phone: "(27)996243739",
    address: "Rua Sete de Setembro n. 13, loja 5",
    facebook: " -",
    instagram: "https://instagram.com/ecopower_vilavelhaes",
    photo: "1PG7RyBY2OGrB7tOjc9RPnrSMplmu_gUk.png",
  },
  {
    municipio: "Serra",
    uf: "ES",
    phone: "(27) 996460202",
    address: "Av: Romulo Castelo, 579, Castelandia",
    facebook:
      "https://www.facebook.com/profile.php?id=100070637298584&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopowerserra.es",
    photo: "1tt-GTYeXZ1o7rLeQQazDfgdsTqXP5iCA.png",
  },
  {
    municipio: "Araras",
    uf: "SP",
    phone: "(19) 99797 0993",
    address: "rua Barão de Arary 424 - centro",
    facebook:
      "https://www.facebook.com/profile.php?id=100092981851631&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopower_ararassp/",
    photo: "1KXvgt9T2ld1uVtFMDmaZTK0FAuLm6d3T.png",
  },
  {
    municipio: "Itaberai",
    uf: "GO",
    phone: "( 62) 9828-8079",
    address: "Rua Nicanor de Farias, 1278",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopower.itaberai",
    photo: "1ea_32nBqaL24eiDLDNYYFwNc-fLPjlvL.png",
  },
  {
    municipio: "São Luís",
    uf: "MA",
    phone: "(98)99971-1247 / (98)98154-7101",
    address:
      "Avenida Contorno Leste, Quadra 19, Loja 3B, Parque Aurora Cohatrac",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopowerenergiasaoluis/",
    photo: "1cDJrGMmlQ6-7Czf-IS546cNtvuFtbJE0.png",
  },
  {
    municipio: "Belo Horizonte 1",
    uf: "MG",
    phone: "(31) 99898-4990",
    address: "Home Office",
    facebook: "https://www.facebook.com/ecopowerbelohorizontemg",
    instagram: "https://www.instagram.com/ecopower_belohorizontemg/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Uberlândia",
    uf: "MG",
    phone: "(34) 98440-9444",
    address: "Rua Santos Dumont, 1310, Lídice",
    facebook: "https://www.facebook.com/energiasolaruberlandia/",
    instagram: "https://www.instagram.com/ecopower_uberlandiamg",
    photo: "1aG9Et0cnqJdkDNi16ABhwc4cnOi79Oup.png",
  },
  {
    municipio: "Belo Horizonte 2",
    uf: "MG",
    phone: "(31) 9 7127-6869/ (31)9 9069-1493",
    address: "Home Office",
    facebook:
      "https://www.facebook.com/profile.php?id=100090355268400&mibextid=LQQJ4d",
    instagram: "https://www.instagram.com/ecopower_belohorizontemg2",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Uba",
    uf: "MG",
    phone: "(32 )999036855",
    address: "Rua Augusto Luiz Barbosa, 25, Bairro Industrial",
    facebook: "https://www.facebook.com/ecopowerubaeregiao",
    instagram: "https://www.instagram.com/ecopower_uba",
    photo: "1K5dxHh09cpFWzJoqYvGiU1cIVNIWbFXY.png",
  },
  {
    municipio: "Poços de Caldas",
    uf: "MG",
    phone: "(35) 98702-1413",
    address: "Rua Correia Neto, 683, Centro",
    facebook: "https://www.facebook.com/ecopowersuldeminas",
    instagram: "https://www.instagram.com/ecopowersuldeminas/",
    photo: "14r7BK9fRJDe4TdmBGVrXDLNOtgqdOk1L.png",
  },
  {
    municipio: "Andradas",
    uf: "MG",
    phone: "(35) 99875-1643",
    address: "Rua Major Bonifácio, 95 Loja 10, Centro",
    facebook: "https://www.facebook.com/profile.php?id=100090522832204",
    instagram: "https://www.instagram.com/ecopower_andradasmg/",
    photo: "1qEnlNlsPp81CR2-NxeFKkSZnQhMqTii_.png",
  },
  {
    municipio: "Dourados",
    uf: "MS",
    phone: "(67) 99801-8394",
    address: "Rua Aquidauana, 726 - sala 09, Jardim Caramuru",
    facebook: "https://www.facebook.com/EcoPowerDouradosMS",
    instagram: "https://www.instagram.com/ecopower_douradosms",
    photo: "1wrG_5oD5jmpRRKxvrGkerZNiMj75aUIW.png",
  },
  {
    municipio: "Amambai",
    uf: "MS",
    phone: "(67) 999741851",
    address: "Home Office",
    facebook: "-",
    instagram: "-",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Campo Grande",
    uf: "MS",
    phone: "(67) 99897.6148",
    address: "Avenida Mato Grosso, 2328 - Jd. dos Estados",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopowercampogrande/",
    photo: "1vYeSROQu7lGNv3gitsW4QbNKk-AgRfOF.png",
  },
  {
    municipio: "Primavera do Leste",
    uf: "MT",
    phone: "(66) 992305335",
    address: "Avenia Cuiabá, 2701, Bairro Primavera II",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopowerprimaveradoleste/",
    photo: "1zcBB84iSrBSzhDzJjCVLeu6j7FYaxZAI.png",
  },
  {
    municipio: "Paranatinga",
    uf: "MT",
    phone: "(66) 98121-1295",
    address: "Avenida Brasil, 1337, Centro",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopowerparanatinga/",
    photo: "1Agd-q_qYqBjQyEHdmnQOo13QirWlqAZW.png",
  },
  {
    municipio: "Juara",
    uf: "MT",
    phone: "(66) 996102295",
    address: "Rua Belo Horizonte,25 N, Centro",
    facebook: "https://www.facebook.com/alvaro.juara",
    instagram: "https://www.instagram.com/ecopower_juara",
    photo: "1waORApl_wmcZCn8mZNaAZhFOHpch3ZQI.png",
  },
  {
    municipio: "Tapurah",
    uf: "MT",
    phone: "(66) 99248-6162",
    address: "Rua Romualdo Allieve,1390, Centro",
    facebook: "https://www.facebook.com/alvaro.juara",
    instagram: "https://www.instagram.com/ecopower_tapurah",
    photo: "1Rsk-uQOHLGLchDCDR4cQ5KB4rC8OWlEI.png",
  },
  {
    municipio: "Rondonópolis ",
    uf: "MT",
    phone: "(66)997218198",
    address: "Avenida Rotary Internacional, 1527, Jardim Participação",
    facebook: "https://www.facebook.com/ecopowerrondonopolismt",
    instagram: "https://www.instagram.com/ecopowerrondonopolis",
    photo: "178SsvxlsW5Zubsiygh7aeSLeiklWv4g4.png",
  },
  {
    municipio: "Caceres",
    uf: "MT",
    phone: "(65) 9996703309",
    address: "AV Dormevil M De Farias, 351, Jardim São Luiz",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower.centrooeste/",
    photo: "1R4WKN8f-L5ecuC5ttv9PQSPHo7MgWzun.png",
  },
  {
    municipio: "Comodoro",
    uf: "MT",
    phone: "(69) 999200113",
    address: "Rua Dos Ipes, 385, Centro",
    facebook: "https://www.facebook.com/EcopowerComodoro",
    instagram: "https://www.instagram.com/ecopowercomodoro/",
    photo: "1Ztzyh90htGTIxI4oLANVjkMpLD2ZwQfh.png",
  },
  {
    municipio: "Lucas do Rio Verde",
    uf: "MT",
    phone: "(65)993002463",
    address: "Av. Amazonas, 572E, Centro",
    facebook: "https://www.facebook.com/EcoPowerLRV.MT",
    instagram: "https://www.instagram.com/ecopowerlucasdorioverde/",
    photo: "1nUZympb0fNLGXJ5jf3z9ma3YosM5hFNM.png",
  },
  {
    municipio: "Conceição do Araguaia",
    uf: "PA",
    phone: "(63) 999186238",
    address: "Avenida Joaquim Lima, bairro São Luís ll ",
    facebook: "https://www.instagram.com/ecopowercda",
    instagram: "https://www.instagram.com/ecopowercda",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Breu Branco",
    uf: "PA",
    phone: "(94) 99296-8694",
    address: "Rua Oswaldo Ferreira N° 306-A  - Centro",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopowerbreubranco",
    photo: "17wtyIvNfJhnZC-CNhVKIJfiN59GrkJlW.png",
  },
  {
    municipio: "Londrina 1",
    uf: "PR",
    phone: "(43) 99154.3315",
    address: "Rua Professor João Candido, 656 - Centro",
    facebook: "https://www.facebook.com/ecopowerlondrina/",
    instagram: "https://www.instagram.com/ecopowerlondrina.oficial/",
    photo: "19COJOn95hYVLh_byY3R8qa1PpkUMWY9l.png",
  },
  {
    municipio: "Paranavaí ",
    uf: "PR",
    phone: "(44) 997224480",
    address: "Capitão Telmo Ribeiro, 1391",
    facebook: "https://www.facebook.com/ecopowerparanavaipr",
    instagram: "https://www.instagram.com/ecopowerpvai",
    photo: "1fVaulm8ncwS4-FMnw59267jkXt7gQU3b.png",
  },
  {
    municipio: "Colorado ",
    uf: "PR",
    phone: "(44) 99814-3230",
    address: "Rua Pernambuco, 449, centro",
    facebook: "https://www.facebook.com/Ecopowercolorado",
    instagram: "https://www.instagram.com/ecopowerenergiacolorado/",
    photo: "1WmzSrOsZSVadJKfFAXZ_uHFt4Yy6RqJw.png",
  },
  {
    municipio: "Londrina 2",
    uf: "PR",
    phone: "(43) 996497263",
    address: "Rua Nevada, n° 639, Quebec",
    facebook:
      "https://www.facebook.com/profile.php?id=100076179608184&mibextid=D4KYlr",
    instagram: "https://www.instagram.com/ecopowerlondrina",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Curitiba",
    uf: "PR",
    phone: "(41) 984101013",
    address: "Pablo Picasso, 92, Fazendinha",
    facebook: "https://www.facebook.com/ECOPOWERCURITIBAENERGIASOLAR",
    instagram: "https://www.instagram.com/ecopowercuritiba/",
    photo: "1gTjVXtGPOWUa0gMoMRnLqyr-nFrCLH2C.png",
  },
  {
    municipio: "Niteroi",
    uf: "RJ",
    phone: "(21) 997629112",
    address: "Av Ewerton da Costa Xavier, 1221",
    facebook: "https://www.facebook.com/ecopowerniteroioceanica",
    instagram: "https://www.instagram.com/ecopowerniteroi",
    photo: "15Pwb-Q_W7TZmK2EVR8zmUgBy5vb7TsKJ.png",
  },
  {
    municipio: "Volta Redonda",
    uf: "RJ",
    phone: "(22) 98117-6888/ (24)97834-6446",
    address: "Rua Oitocentos e Cinquenta e Quatro, 180, Jardim Tiradentes",
    facebook: "https://www.facebook.com/ecopowersulfluminense",
    instagram: "https://www.instagram.com/ecopower_sulfluminense/",
    photo: "1WLURz2hgpv-QgVglY31eT303QnriPkX7.png",
  },
  {
    municipio: "Jaru ",
    uf: "RO",
    phone: "(69) 993278752",
    address: "Av Rio Branco 2475 setor 5",
    facebook: " -",
    instagram: "-",
    photo: "1JItg9b_FPdf498Lro19DC7Uq5paHKPp9.png",
  },
  {
    municipio: "Vilhena ",
    uf: "RO",
    phone: "(69) 999210113",
    address: "Av José do Patrocínio 3496 Centro",
    facebook: "https://www.facebook.com/ecopowervilhenaroo",
    instagram: "https://www.instagram.com/ecopower_vilhenaro/",
    photo: "1vdFhj1rhrP0BmgNrlyltu-y_ffZBHuj.png",
  },
  {
    municipio: "Esteio",
    uf: "RS",
    phone: "(51) 99847 7936",
    address: "Rua 24 de Agosto 1449 sala 3 Centro Esteio",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopoweresteio",
    photo: "15N-ZJ1tPVE1oqEV7jbTXHwG-cc-fP-X1.png",
  },
  {
    municipio: "Novo Hamburgo ",
    uf: "RS",
    phone: "(51) 35948488 / (53) 981087187",
    address: "Rua Vinte e cinco de julho, 424 - Bairro Rio Branco",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_novohamburgors",
    photo: "1odEZKMZ1kz2_HoB06m1z4Zo9krbt1LEE.png",
  },
  {
    municipio: "Pelotas",
    uf: "RS",
    phone: "(53)999059686/ (53) 33250893",
    address: "Rua benjamin constant, 1169 - Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerunidadepelotas",
    photo: "1S2KAwC986Lp3OyPmSZm7ty5RopG1ak5w.png",
  },
  {
    municipio: "Gravataí",
    uf: "RS",
    phone: "(51) 31280303",
    address: "Luis Arlindo Jaeger, 166, Salgado Filho",
    facebook: "https://www.facebook.com/ecopowergravatai",
    instagram: "https://www.instagram.com/ecopower_gravatairs",
    photo: "1cVtUiCo36h8rSRPq0pcgF41VmFSalanU.png",
  },
  {
    municipio: "Curitibanos",
    uf: "SC",
    phone: "(49)3191-0181",
    address: "Rua Paulo Pedro Pereira, 410, Bairro Nossa Senhora Aparecida",
    facebook:
      "https://www.facebook.com/profile.php?id=100076069398881&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopowercuritibanos/",
    photo: "IMG-20240411-WA0039_Douglas%20Bianki%20Perio.jpg"
  },
  {
    municipio: "Joinville",
    uf: "SC",
    phone: "(47) 99803-5982",
    address: "Rua Manoel Francisco de Oliveira, 350 C1 , Bairro Aventureiro",
    facebook: "https://www.facebook.com/EcoPowerEnergiaSolarJoinville",
    instagram: "https://www.instagram.com/ecopower_joinville/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "São José do Rio Preto",
    uf: "SP",
    phone: "(17) 99180-0154",
    address: "Rua Antonio Da Silveira, 1.470",
    facebook: "https://www.facebook.com/ecopowersjriopretosp",
    instagram: "https://www.instagram.com/ecopowerriopretooficial/",
    photo: "1nfqqMEOjVmKEG7tteMOL-lu6DbIAEDnr.png",
  },
  {
    municipio: "Sao Paulo ",
    uf: "SP",
    phone: "(11) 93444-6439",
    address: "Tenente Gelas 260 - Tatuapé",
    facebook: "https://www.facebook.com/ecopowersaopaulozonaleste",
    instagram: "https://www.instagram.com/ecopower_saopaulozonaleste",
    photo: "1P5RF4ysF6Splly6GKu7JxH13paFtrm-L.png",
  },
  {
    municipio: "Botucatu",
    uf: "SP",
    phone: "(14)  99890-5028",
    address: "Avenida Camilo Mazoni , 1554 - Jardim Paraiso",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower.botucatu/",
    photo: "1pE2H46ZvXJchRO-AlCshEgEDIPNLJkTi.png",
  },
  {
    municipio: "Pindorama",
    uf: "SP",
    phone: "(17) 99701-8823",
    address: "Rua XV de Novembro, 524",
    facebook:
      "https://www.facebook.com/profile.php?id=100076492922255&mibextid=D4KYlr",
    instagram: "https://www.instagram.com/ecopower_pindoramasp/",
    photo: "1vEAh4VJ4vTqfznTsADR1--Db1QibNCe6.png",
  },
  {
    municipio: "Santa Adelia",
    uf: "SP",
    phone: "(17)996061258",
    address: "Avenida Dr Luiz Dumont, 260",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_santaadelia/",
    photo: "1NUg9M8ih_RYoIb8D3JAHrmJ0cdxSUMK-.png",
  },
  {
    municipio: "Praia Grande",
    uf: "SP",
    phone: "(13)99801- 6777",
    address: "Avenida Kennedy, 1446, Vila Guilhermina",
    facebook: "https://www.facebook.com/profile.php?id=100090915160750",
    instagram: "https://www.instagram.com/ecopower_praiagrandesp/",
    photo: "1sbp7Z45NKJLVA2X2o_ISt3ipIREyWUBq.png",
  },
  {
    municipio: "Boituva",
    uf: "SP",
    phone: "(15) 991382000",
    address: "Av Pereira Inacio, 304 - Sala 3 - Centro",
    facebook: "https://www.facebook.com/ecopowerboituva",
    instagram: "https://www.instagram.com/ecopowerboituva",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Sorocaba",
    uf: "SP",
    phone: "(15)-981493699",
    address: "Rua Miranda Azevedo 375,  Centro",
    facebook: "https://www.facebook.com/ecopowersorocabasp",
    instagram: "-",
    photo: "14qoSTMtEtdyj9kSh4FrBmpvkL-gQnvTJ.png",
  },
  {
    municipio: "Orlandia",
    uf: "SP",
    phone: "(17)981393779",
    address: "Rua 6, numero 123a, Jardim Boa vista",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopower_orlandiasp/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Porto Feliz ",
    uf: "SP",
    phone: "(15) 99683-5263",
    address: "Alameda dos Canários 85 - Jardim Tendá",
    facebook: "https://www.facebook.com/profile.php?id=61550953990455",
    instagram: "https://www.instagram.com/ecopower_portofelizsp",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Monte Alto",
    uf: "SP",
    phone: "(16) 3240-0303",
    address: "AVENIDA JOSÉ CUPERTINO BOTO ,484 - CENTRO",
    facebook: " https://www.facebook.com/ecopowermontealto/ ",
    instagram: "https://www.instagram.com/ecopower_montealtosp/",
    photo: "1Rade12vhiYPdPbRKvbTqLkIgTAPi_gpx.png",
  },
  {
    municipio: "Tanabi",
    uf: "SP",
    phone: "(17)981021616",
    address: "Av Ulysses Guimaraes 11 PQ Res Nova Tanabi",
    facebook: "https://www.facebook.com/ecopowertanabisp",
    instagram: "https://www.instagram.com/ecopowertanabisp",
    photo: "1akwH0zT13a9lmucOtPM4lIQQWBQbcYY7.png",
  },
  {
    municipio: "Artur Nogueira",
    uf: "SP",
    phone: "(19) 974055279",
    address: "Rua Ernesto Tagliari, 1084",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_arturnogueira/",
    photo: "1mHK24Jys7K5o7gpjnJFXz8Ab85x0O2Hi.png",
  },
  {
    municipio: "Iracemapolis",
    uf: "SP",
    phone: "(19) 998055168",
    address: "R Alcilene Selestino Oflaherty, 175, Recanto Das Paineiras",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_iracemapolis/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Taquaritinga",
    uf: "SP",
    phone: "(16) 98188-2967",
    address: "R. Prudente de Moraes, 632 - Centro",
    facebook: "https://www.facebook.com/profile.php?id=100090813537724",
    instagram: "-",
    photo: "19BmOzulMkrP0CogCbXfKZABQqRM6AfA4.png",
  },
  {
    municipio: "Ibitinga",
    uf: "SP",
    phone: "(16) 98188-2967",
    address: "Avenida Vitor maida, 865 - Centro",
    facebook: "https://www.facebook.com/profile.php?id=100092335995674",
    instagram: "https://www.instagram.com/ecopower_ibitingasp/",
    photo: "1-jlZwrhhu048Osei8BdjPwrzWs5EyXGx.png",
  },
  {
    municipio: "Catanduva",
    uf: "SP",
    phone: "(17) 991842077",
    address: "R Borborema 351, Jd Brasil",
    facebook: "https://www.facebook.com/ecopower_catanduva/",
    instagram: "https://www.instagram.com/ecopower_catanduva/",
    photo: "1UWXxjWT2TWD0GpZM4eVQkrZphAJxVzJm.png",
  },
  {
    municipio: "Laranjal Paulista ",
    uf: "SP",
    phone: "(15 ) 996724671",
    address: "Av. Prefeito Hermelindo Pillon, 450 - Jd Elite",
    facebook: "https://www.facebook.com/ecopowerlaranjalpaulista",
    instagram: "https://www.instagram.com/ecopower_laranjalpta/",
    photo: "1sxdtUPnttYWGlKIqC5e0VzPTcvBVP3xM.png",
  },
  {
    municipio: "Barretos",
    uf: "SP",
    phone: "(17) 99128-9101 / 17 98149-5771",
    address: "Av. Derby Clube, 100 - Derby Clube / Boulevard dos Coqueiros",
    facebook: " -",
    instagram: "https://www.instagram.com/ecopower_barretossp/",
    photo: "1_0l29ITg-Dx9zyXk8jTd2rOMn5p5AYfv.png",
  },
  {
    municipio: "Mogi Guaçu",
    uf: "SP",
    phone: "(19) 99895-3533 / 19 98991-3080 / 19 99976-8696",
    address: "Avenida Brasil , 5060 , Jardim Serra Dourada",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowermogiguacu/",
    photo: "1LU07MNK10IwcJGhi37MVqhF92vXcF1y-.png",
  },
  {
    municipio: "São João Da Boa Vista",
    uf: "SP",
    phone: "(19) 999218486",
    address: "Rua Orlando Fracari, 196 - Recanto do Bosque",
    facebook: "https://www.facebook.com/ecopowersjbv",
    instagram: "https://www.instagram.com/ecopowersjbv",
    photo: "1zGfYGvm0tsQv-dYKwXNTbkJCC_O5oQBL.png",
  },
  {
    municipio: "São Carlos",
    uf: "SP",
    phone: "(16) 31160946",
    address: "Rua 28 De Setembro, 2311, Centro",
    facebook: "https://www.facebook.com/profile.php?id=100076569025294",
    instagram: "https://www.instagram.com/ecopowersaocarlos/",
    photo: "1d46BifQjWPQxqSCT17DpnB52XIrdh6qk.png",
  },
  {
    municipio: "São Paulo",
    uf: "SP",
    phone: "(11) 99266-7085",
    address: "Av. Clavásio Alves da Silva, 227 - Sala 103 - Vila Siqueira",
    facebook:
      "https://www.facebook.com/p/EcoPower-S%C3%A3o-PauloSP3-100083050246301",
    instagram: "https://www.instagram.com/ecopower_saopaulosp3/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Ribeirão Pires-SP ",
    uf: "SP",
    phone: "(11) 96261-1140",
    address: "Rua Felipe Sabbag, 200 - Centro",
    facebook: "https://www.facebook.com/EcopowerRibeiraoPires/",
    instagram: "https://www.instagram.com/ecopowerribeiraopires/",
    photo: "1T7eOi5Ok-SWPkHqhPbP9rRaDIYsdD1U6.png",
  },
  {
    municipio: "Santana de Parnaiba ",
    uf: "SP",
    phone: "(11) 988378281",
    address: "Estrada Municipal Bela Vista, 917",
    facebook: "-",
    instagram: "https://www.instagram.com/ronaldoecopower/",
    photo: "11D2oUQcUESfuf6SnNLKYrcxpgpcmX8VC.png",
  },
  {
    municipio: "Araçatuba",
    uf: "SP",
    phone: "(18) 998244054",
    address: "Rua Humaitá, 1070 - Jd. Sumaré",
    facebook: "https://www.facebook.com/ecopoweraracatuba/",
    instagram: "https://www.instagram.com/ecopoweraracatuba/",
    photo: "1oX1e8GbagJmamLvUAVY0PX7AWtH62fdC.png",
  },
  {
    municipio: "Araraquara",
    uf: "SP",
    phone: "(16) 99204-0740",
    address:
      "Av. Octaviano de Arruda Campos, 921, Vila Cidade Industrial (Vila Xavier)",
    facebook: "https://www.facebook.com/ecopowerararaquara",
    instagram: "https://www.instagram.com/ecopowerararaquara/",
    photo: "18w-kIyTfisuG55FCp1XyJ8YFbEy8WA4G.png",
  },
  {
    municipio: "Matupá",
    uf: "MT",
    phone: "66996832467",
    address: "Luiz Mena, 201, Sala 05, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowermatupa/",
    photo: "1b4CV51zrw1LST_wqrryZ54pNIZP5OQ0n.png",
  },
  {
    municipio: "Peixoto de Azevedo",
    uf: "MT",
    phone: "66996832467",
    address: "Em breve novo endereço",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerpeixotodeazevedo/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Patrocinio",
    uf: "MG",
    phone: "34998115456",
    address: "Avenida Jacinto Barbosa, 104 São Francisco ",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerptc/",
    photo: "1kShJqJYc2l3PSZyDDXmXz1gt--tqL-Lk.png",
  },
  {
    municipio: "Botelhos",
    uf: "MG",
    phone: "(35) 99877-8211",
    address: "Av. Dr. Hélio Andrade Alves, 724 D - Boa Vista",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_botelhosmg/",
    photo: "1YwiFAbdMn4x9ytwJaane09NTOA8jLROY.png",
  },
  {
    municipio: "Cunha",
    uf: "SP",
    phone: "19 991647602 ",
    address: "Rodovia SP171 km45 Posto BR Petrobras ",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_cunhasp/",
    photo: "10yG54QPMOaITOv81bKrQdNxTfIEKRhrZ.png",
  },
  {
    municipio: "Parobé",
    uf: "RS",
    phone: "51994598122",
    address: "Av das Nasções 1945 , Nova Guaruja ",
    facebook: "https://www.facebook.com/ecopowerparobe/",
    instagram: "-",
    photo: "1HjyTRKQvZNy1TwjNmHyskcpnnGVD9VFb.png",
  },
  {
    municipio: "Goioere",
    uf: "PR",
    phone: "(44)99959-0836",
    address: "Rua Jose Bonifacio, 555, Centro",
    facebook: "https://www.facebook.com/Ecopowergoioere/",
    instagram: "https://www.instagram.com/ecopowergoioere/",
    photo: "1edjElx97bOB-DR3ZglmOdTRieeMDqQMV.png",
  },
  {
    municipio: "Tangará da Serra",
    uf: "MT",
    phone: "(65) 99651-2694",
    address: "Av Tancredo de Almeida Neves, n° 209-E, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_mt",
    photo: "1EkwvdFU6LX1-N1nbnav9G1rXCIY-W4yb.png",
  },
  {
    municipio: "Juína",
    uf: "MT",
    phone: "66-992825255",
    address: "Rua Dos Canários ",
    facebook: "https://www.facebook.com/ecopowerjuina",
    instagram: "https://www.instagram.com/ecopower_juina",
    photo: "1ZSEC8QIaKSOMUjwyAGSpc3GVK4BgqzBt.png",
  },
  {
    municipio: "Três Lagoas",
    uf: "MS",
    phone: "67 9 9906-6404",
    address: "Av. Rosario Congro, 1961 Colinos",
    facebook: "https://www.facebook.com/ecopowertreslagoas",
    instagram: "https://instagram.com/ecopowertreslagoas",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Paranaíba",
    uf: "MS",
    phone: "67 9 8111-5919",
    address: "Av. Aristides Klafke, 1594 JD São José",
    facebook: "-",
    instagram: "-",
    photo: "1KrVcb-0Smk5oq_D9oIMWVk2-XdZlfbzS.png",
  },
  {
    municipio: "Bauru ",
    uf: "SP",
    phone: "14991833304",
    address: "Demetrio Arieta, 36,  Jardim Carolina ",
    facebook: "-",
    instagram: "-",
    photo: "1Jmmz3H1Tfl3xFsLblG0dddcFu6Y3uSoQ.png",
  },
  {
    municipio: "Tramandaí ",
    uf: "RS",
    phone: "51-996826320 ",
    address: "Rua Egon Hoffmeistern, 889, São Francisco",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_tramandairs",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Maracaju",
    uf: "MS",
    phone: "67998018394",
    address: "Rua Melanio Garcia Barbosa, 441",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_maracajums/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Bebedouro",
    uf: "SP",
    phone: "16- 98858-0085",
    address: "Praça Nove De Julho,81 SA 2, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerbebedouro/",
    photo: "1bf0nDCjF_RwgFx2PwVYFHDS-ZFPSW-iq.png",
  },
  {
    municipio: "Agua Boa",
    uf: "MT",
    phone: "67998018394",
    address: "Rua 01, 567",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_aguaboa",
    photo: "1S6sk6ArYUU_2W45x_RqhPay76iyXdJ01.png",
  },
  {
    municipio: "Governador Valadares",
    uf: "MG",
    phone: "33 988596504",
    address: "Rua Luiz Ensch 144, Grã Duquesa",
    facebook: "https://www.facebook.com/ecopowergovernadorvaladaresmg",
    instagram: "https://www.instagram.com/ecopower_gv/",
    photo: "1sTY4wqx3tvTljsBZNIPPzoACDgv2qHMC.png",
  },
  {
    municipio: "Goiania",
    uf: "GO",
    phone: "62 98127-6353",
    address: "Rua 69-A, n 321. Salas 09-10. Setor Norte Ferroviário",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowergoias",
    photo: "19uOL-4XwK0hWToaK_1we_Usq2b_2-oW8.png",
  },
  {
    municipio: "Sinop",
    uf: "MT",
    phone: "(66) 9 9625-2682",
    address: "Rua Das Orquideas, 1015, Centro",
    facebook: "https://www.facebook.com/ecopowersinopmt",
    instagram: "https://www.instagram.com/ecopowersinopmt",
    photo: "1TpiTbZwFOrSSlweEphth3JQDQJsn1rcF.png",
  },
  {
    municipio: "Recife",
    uf: "PE",
    phone: "(81) 9 7902-1713",
    address: "Av. Visconde de Jequitinhonha nº 209 - Sala 806 - Boa Viagem",
    facebook: "-",
    instagram: "-",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Barreiras ",
    uf: "BA",
    phone: "77999325405",
    address: "Em breve endereço",
    facebook: "https://www.facebook.com/ecopoweroestebaiano",
    instagram: "https://www.instagram.com/ecopoweroestebaiano/",
    photo: "1greAvUbyUG9lSuJtvsmq8ZOKpypvFk4e.png",
  },
  {
    municipio: "Santo Antônio de Pádua",
    uf: "RJ",
    phone: "(22) 981655100",
    address: "Rua Silva Jardim, 30 centro ",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerpadua/",
    photo: "1haktwyJHv4VNdhufjfw_mQ3SsTF5LCAZ.png",
  },
  {
    municipio: "Jaboticabal",
    uf: "SP",
    phone: "(16) 3204-4073",
    address: "Praça Duilio Poli, 83 Nova Jaboticabal",
    facebook: "https://www.facebook.com/ecopowerjaboticabalsp",
    instagram: "https://www.instagram.com/ecopowerjaboticabalsp",
    photo: "1SAZYNQ3lNLZAG3JugFLLtP8vTQ2fE4_Z.png",
  },
  {
    municipio: "Juiz de Fora",
    uf: "MG",
    phone: "(32)99982-9945",
    address: "Rua Orestes Fabiano Alves, 22, São Pedro",
    facebook:
      "https://www.facebook.com/profile.php?id=100087129319843&mibextid=LQQJ4d",
    instagram: "https://www.instagram.com/ecopower_juizdeforamg",
    photo: "1BX5Jrgz9bkQinzBvVn3cSoxAO9bFVDVm.png",
  },
  {
    municipio: "Apucarana",
    uf: "PR",
    phone: "43 996340704",
    address: "Rua Clóvis da Fonseca, 547, centro",
    facebook: "https://www.facebook.com/EcoPowerApucarana",
    instagram: "https://www.instagram.com/pr_ecopowerenergia/",
    photo: "1sIjqJm7mQxWfBUccnTNUywwZ20YwOtZV.png",
  },
  {
    municipio: "Catalão",
    uf: "GO",
    phone: "64 984252004",
    address: "Rua 522, NR-201, Santa Cruz",
    facebook: "https://www.facebook.com/ecopowercatalaogo/",
    instagram: "https://www.instagram.com/ecopower_catalaogo/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Imperatriz",
    uf: "MA",
    phone: "999905-0885 ",
    address: "Rua Piaui, 340B  Nova Imperatriz ",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerunidadeimperatriz",
    photo: "1Ve5tLBZxnA74ePtSP0gnNLodJuGP3Utu.png",
  },
  {
    municipio: "São Paulo",
    uf: "SP",
    phone: "11 93444-6439",
    address: "Estrada das Lagrimas 1760. ",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_saopaulozonaleste",
    photo: "14UMkZNzrDk7rH12lCbh4fDAwXq0bYWJG.png",
  },
  {
    municipio: "Campo Novo do Parecis ",
    uf: "MT",
    phone: "(65) 99316-0867",
    address: "Avenida Porto Velho, n° 394-NE, sala 02",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_mt",
    photo: "11OBSQz0tRqVXrapwX-ObPvFTXHD4vAdX.png",
  },
  {
    municipio: "Unai",
    uf: "MG",
    phone: "(38) 99809-0275",
    address: "Rua Canabrava, 1240, Cachoeira",
    facebook: "-",
    instagram: "https://www.instagram.com/ECOPOWER_UNAIMG/",
    photo: "1oRi_TI-SGY5GBQzjbkbccDDvGbD63nac.png",
  },
  {
    municipio: "Nova Mutum",
    uf: "MT",
    phone: "(65) 92101-2099",
    address: "Avenida das Águias, n° 486-W, sala 03",
    facebook: "-",
    instagram: "https://instagram.com/ecopower_mt",
    photo: "1D31cnjJHrlFNIH7Nt95cq7tcCEXPcg4N.png",
  },
  {
    municipio: "Lençóis Paulista ",
    uf: "SP",
    phone: "14 991485853",
    address: "Av. Ubirama 469 Villa Nossa Senhora Aparecida ",
    facebook: "-",
    instagram: "https://www.instagram.com/Ecopower_lencoispaulistassp/",
    photo: "1o6VYZQY_DKnkDQ7M1L3caNzfZHhJlA9M.png",
  },
  {
    municipio: "São Paulo",
    uf: "SP",
    phone: "1199720-4889",
    address: "Home Office",
    facebook: "https://www.facebook.com/EcoPowerPaulista/",
    instagram: "https://www.instagram.com/ecopower_paulista/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Rio de Janeiro",
    uf: "RJ",
    phone: "(21)98169-6566",
    address: "Home Office",
    facebook: "-",
    instagram: "-",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "São Paulo",
    uf: "SP",
    phone: "(11)95659-8181",
    address: "Home Office",
    facebook: "https://www.facebook.com/ecopower.saopaulosp",
    instagram: "https://www.instagram.com/ecopower.saopaulo",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Brasilia",
    uf: "DF",
    phone: "6184916101",
    address: "Home Office",
    facebook: "https://www.facebook.com/ecopowerbrasiliadf",
    instagram: "https://www.instagram.com/ecopower_brasiliadf/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "São Luís ",
    uf: "MA",
    phone: "98970187747",
    address: "São Luís ",
    facebook: "https://www.facebook.com/ecopowerenergiasolarslma",
    instagram: "https://www.instagram.com/ecopower_saoluisma2",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Uaua",
    uf: "BA",
    phone: "74 99966 1618",
    address: "Rua Jeronimo De Sá Rodrigues, 55, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerenergiasolar_nosertao",
    photo: "1c5ok7bUe6c4T_DRowbXFmcav2Wti7Fx1.png",
  },
  {
    municipio: "Canudos",
    uf: "BA",
    phone: "74999661618",
    address: "Av JK, S/N, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerenergiasolar_nosertao",
    photo: "1I9r070RjjpkjpAK7tugMoiHCh3xV4GNE.png",
  },
  {
    municipio: "Euclides Da Cunha",
    uf: "BA",
    phone: "74 99966 1618",
    address: "AV ALMERINDO REHEM S/N CENTRO",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerenergiasolar_nosertao",
    photo: "1SRBUUpQs_3cWNLGSQo22C9GUMil27Rom.png",
  },
  {
    municipio: "Nanuque ",
    uf: "MG",
    phone: "33 998585049",
    address: "Avenida Santos Dumont, 383, Centro",
    facebook: "https://www.facebook.com/ecopowernanuque",
    instagram: "https://www.instagram.com/ecopower.nanuquemg/",
    photo: "1_Zt1sHqGjFqCygbGjW6Kmx6AXahXUaQm.png",
  },
  {
    municipio: "São Gonçalo",
    uf: "RJ",
    phone: "21 98694-5453",
    address: "Rua Dr Nilo Peçanha, 1031 loja 02 Nova Cidade",
    facebook: "https://www.facebook.com/ecopowerlestefluminense",
    instagram: "https://www.instagram.com/ecopowerlestefluminense/",
    photo: "1CDAcrBK2c6EocX-7Kv9vRhVKXyH5DSQ2.png",
  },
  {
    municipio: "Toledo",
    uf: "MG",
    phone: "(35) 9 9708-5516",
    address: "Rua Direita, 101, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_toledomg",
    photo: "12h-HGwUeMPvM95eSGvgwd_G_-tXpq0wI.png",
  },
  {
    municipio: "Santo André ",
    uf: "SP",
    phone: "11 998033344",
    address: "Rua das Figueiras,1606 Bairro Campestre ",
    facebook: "https://www.facebook.com/ecopowersantoandresp",
    instagram: "https://www.instagram.com/ecopowersantoandresp",
    photo: "1Y4tjazSR2HjEMeDtwUxI-RhT7o0hv6NP.png",
  },
  {
    municipio: "Guarulhos ",
    uf: "SP",
    phone: "11 94986-0775",
    address: "Home office",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerguarulhos",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Limeira",
    uf: "SP",
    phone: "19991998951",
    address: "São Vicente de Paula, 18b, Vila Cristovan",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopower_limeira",
    photo: "1l3a60Lp1yrb8g8H_J5r-2ts7OpGSQb_h.png",
  },
  {
    municipio: "Americana",
    uf: "SP",
    phone: "19995364776",
    address: "R. Washington Luís, 514 - Centro, Americana",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopoweramericana",
    photo: "1Q_1nCLP8i3mUK8kushDpMkzfZ6N-AJgz.png",
  },
  {
    municipio: "Olimpia",
    uf: "SP",
    phone: "17 99144-8007",
    address: "Rua Dr. Antonio Olimpio, 625 B, Centro",
    facebook: "https://www.facebook.com/ecopowerolimpia",
    instagram: "https://www.instagram.com/ecopower.olimpia/",
    photo: "1ScMHRrRjGKLeLkbdvDLHZLhOhBplQqC1.png",
  },
  {
    municipio: "Taubaté",
    uf: "SP",
    phone: "12 98294-1855",
    address: "Home Office",
    facebook: "https://www.facebook.com/ecopowertaubatesp",
    instagram: "https://www.instagram.com/ecopower_taubatesp/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Ribeirão Preto",
    uf: "SP",
    phone: "(16) 99797-4401",
    address: "Av. Independência, 182, Centro",
    facebook: "-",
    instagram: "https://www.instagram.com/ecopowerribeirao/",
    photo: "1KL4VeOKiS0Ez6EG5WQr2CGSZvjBoZGdb.png",
  },
  {
    municipio: "Campos dos Goytacazes ",
    uf: "RJ",
    phone: "22998131160",
    address: "Rua Barão da lagoa Dourada 453 pq Pelinca ",
    facebook: "",
    instagram: "https://www.instagram.com/ecopower_rj_es/",
    photo: "1kJ0BBjb6FLnbgOJaaMuWL-YmpwtXyRCn.png",
  },
  {
    municipio: "Piracicaba ",
    uf: "SP",
    phone: "(19) 9.8280-0003",
    address: "Av. Presidente Kennedy, 334 Nova Piracicaba ",
    facebook: "https://www.facebook.com/EcoPowerPiracicabaeregiao",
    instagram: "https://www.instagram.com/ecopower_piracicabasp/",
    photo: "1Lf-b-AIefepUVLALcvrd_byAbNW6FtPR.png",
  },
  {
    municipio: "União dos Palmares ",
    uf: "AL",
    phone: "82991417564",
    address: "Home Office",
    facebook: "-",
    instagram: "-",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Marilia",
    uf: "SP",
    phone: "14991425021",
    address: "Avenida Pedro de Toledo, Sala D, 2480, Palmital",
    facebook: "",
    instagram: "https://www.instagram.com/ecopower_mariliasp/",
    photo: "1FUJUcvff51rEoQJ9q4eBM3RiHJP-yRVs.png",
  },
  {
    municipio: "Lages",
    uf: "SC",
    phone: "(49) 9 8824-3650",
    address: "Av. Marechal Floriano, 1160 - centro",
    facebook: "https://www.facebook.com/ecopowerlages",
    instagram: "https://instagram.com/ecopower_lagessc",
    photo: "1fE7vStXYSbpxtPFceS9_eXG45rl_B6VI.png",
  },
  {
    municipio: "Sertãozinho",
    uf: "SP",
    phone: "16 99185 7062 - 99190 3147 ",
    address: "Rua Dr. Olidair Ambrósio, 1223B, Centro",
    facebook: "https://www.facebook.com/profile.php?id=100077708711833",
    instagram: "https://www.instagram.com/ecopower.sertaozinhosp/",
    photo: "1_6h_LwJAItwb1iqhRlDjpW4pEuCcXuf2.png",
  },
  {
    municipio: "Guarantã do Norte-MT ",
    uf: "MT",
    phone: "65999599758",
    address: "Avenida Curitiba N° 1565, Jardim Vitória ",
    facebook:
      "https://www.facebook.com/profile.php?id=100083247525321&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopower_guarantadonorte",
    photo: "1XlnGlgoiV1LkTu5IpKTWlK9dqNjUtclR.png",
  },
  {
    municipio: "Porto Alegre",
    uf: "RS",
    phone: "51 99645 0896",
    address: "Home Office",
    facebook: "-",
    instagram: "-",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png",
  },
  {
    municipio: "Santo Estevão ",
    uf: "BA",
    phone: "75)9 9128-2358",
    address: "Av Dom José Botelho,n°351",
    facebook: "https://www.facebook.com/ecopowerST",
    instagram: "https://www.instagram.com/ecopower_santoestevaoba/",
    photo: "1ZXcc9qiECUdXUxnUhsk_cX4gwlyU_qg8.png",
  },
  {
    municipio: "Balsas",
    uf: "MA",
    phone: "(86) 9 9813-8232",
    address: "Av Catulo, 43, Centro",
    facebook: "-",
    instagram: "-",
    photo: "1-iPGTLauf4l7reIx8zRGoQkLugUTzcBq.png",
  },
  {
    municipio: "Uruçui",
    uf: "PI",
    phone: "(86) 9 9813-8232",
    address: "Av. Santos Dumont, S/N, Sala 01, Aeroporto",
    facebook: "-",
    instagram: "-",
    photo: "1j9UiIwb_vZiK1Dyq2nlEdNyEN-DHa49X.png",
  },
  {
    municipio: "Tianguá",
    uf: "CE",
    phone: "(86) 9 9813-8232",
    address: "Rua Zeferino Ferreira, 1153, Regis Diniz",
    facebook: "-",
    instagram: "-",
    photo: "1K0LCkG4ddvP7FzO0nOMMvzhW5L_RObVL.png",
  },
  {
    municipio: "São José do Rio Claro",
    uf: "MT",
    phone: "(65) 9 9954-2797",
    address: "Rua Guanabara, 428, Centro",
    facebook: "https://www.facebook.com/ecopowersjrioclaromt",
    instagram: "https://www.instagram.com/daniel.energiasolar_mt",
    photo: "1961yjPU6torlZ-gUsqhc-BPrsT4Txzs6.png",
  },
  {
    municipio: "JAGUARE",
    uf: "ES",
    phone: "(27) 99839-6111",
    address: "AVENIDA 9 DE AGOSTO 349, CENTRO",
    facebook: "-",
    instagram: "",
    photo: "AVENIDA-9-DE-AGOSTO-349.jpeg"
  },
  {
    municipio: "Posto da mata",
    uf: "BA",
    phone: 73999266796,
    address: "Av João Durval Carneiro 734",
    facebook: "https://www.instagram.com/juliodiasevan?igsh=dDg2bzdtaWNoeGhk&utm_source=qr",
    instagram: "https://www.instagram.com/juliodiasevan?igsh=dDg2bzdtaWNoeGhk&utm_source=qr",
    photo: "image_Julio%20Neto%20Dias%20Evan.jpg"
  },
  {
    municipio: "Conceição do Araguaia",
    uf: "PA",
    phone: "63999186238 e 94992243058",
    address: "Avenida 7de Setembro, 118 - Centro",
    facebook: "",
    instagram: "",
    photo: "IMG_20211029_180045_Original_Paulo%20Cunha.jpg"
  },
  {
    municipio: "Jacarei",
    uf: "SP",
    phone: 12991279061,
    address: "Av das Letras, 26 Lj07- Vila Branca Center- Vila Branca Cep: 12301330",
    facebook: "https://www.facebook.com/share/HA8fmw4uAXfAxNHW/?mibextid=qi2Omg",
    instagram: "https://www.instagram.com/ecopower_jacarei?igsh=dmk5ZDg0MnJ1Zm93",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "João Pessoa",
    uf: "PA",
    phone: "83 3690-1688 ou 83 99120-3333",
    address: "Av Presidente Epitácio Pessoa, 201 - Sala 108 - Bairro Estados - João Pessoa/SP",
    facebook: "https://www.facebook.com/ecopowerjoaopessoapb?mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopower_joaopessoa?igsh=bGxxeTE1ZGlsdGNm",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Campina Grande",
    uf: "PA",
    phone: "83 99120-3333",
    address: "Rua Presidente Epitácio Pessoa, 149 Centro",
    facebook: "https://www.facebook.com/ecopowercityviradourosp?mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopower_campinagrande?igsh=M3I2azVobHl0Yjcz",
    photo: "IMG-20240328-WA0022_Claudenilson%20De%20Souz.jpg"
  },
  {
    municipio: "São José do Rio Claro",
    uf: "MT",
    phone: "65992331644 /  65999542797",
    address: "Rua Guanabara, 428, Centro",
    facebook: "https://www.facebook.com/ecopowersjrioclaromt",
    instagram: "https://www.instagram.com/ecopower_energiasolar_sjrcmt?utm_source=qr&igsh=MXY5cW1vb3Zrb3FiNA==",
    photo: "fachada%20loja_Elaine%20Cristina%20De%20A.jpeg"
  },
  {
    municipio: "Guarujá",
    uf: "SP",
    phone: 13996504865,
    address: "Rua Áureo Guenaga de Castro 64, Parque Enseada , Guarujá , SP",
    facebook: "https://www.facebook.com/ecopowerguarujasp",
    instagram: "https://www.instagram.com/ecopower_guaruja/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Goiânia",
    uf: "GO",
    phone: "62 3928-1016",
    address: "R. 69-A, 321, salas 9 e 10 - Setor Norte Ferroviário",
    facebook: "https://www.facebook.com/ecopowergoianiago/",
    instagram: "https://www.instagram.com/ecopowergoias/",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Campo Mourão",
    uf: "PA",
    phone: 44999346943,
    address: "Rua Brasil, 1559, sala",
    facebook: "https://www.facebook.com/ecopowercm",
    instagram: "https://www.instagram.com/ecopowercm/",
    photo: "IMG_1135_NATALIA%20VENANCIO%20DE.jpeg"
  },
  {
    municipio: "Dourados, Agua Boa, Canarana, Maracaju",
    uf: "MS e MT",
    phone: "67 999182377",
    address: "Rua Aquidauana, 726 - sala 09 - Jardim Caramuru - Dourados ms",
    facebook: "https://www.facebook.com/EcoPowerDouradosMS",
    instagram: "https://www.instagram.com/ecopower_douradosms?igsh=bHR5OTNwbGdhMjU2",
    photo: "Rua-Aquidauana.jpg"
  },
  {
    municipio: "Sumare",
    uf: "SP",
    phone: "19 99300-5885",
    address: "Av José Mancini 283 jardim São Carlos",
    facebook: "https://www.facebook.com/share/h8QFV26ojnjuWc9M/?mibextid=WC7FNe",
    instagram: "https://www.instagram.com/ecopower_sumaresp?igsh=dmk4b3M3dDlqanph",
    photo: "IMG_9250_Marcio%20Henrique%20Fagi.jpeg"
  },
  {
    municipio: "Lages",
    uf: "SC",
    phone: 49991678772,
    address: "Av. Mal. Floriano, 1160 - Centro",
    facebook: "https://www.facebook.com/ecopowerlages",
    instagram: "https://www.instagram.com/ecopower_lagessc/",
    photo: "Faxada%20loja%20lages_Carlos%20Alberto%20Amori.jpg"
  },
  {
    municipio: "São Roque",
    uf: "SP",
    phone: "11 956198759",
    address: "",
    facebook: "https://www.facebook.com/profile.php?id=61550621180915&mibextid=ZbWKwL",
    instagram: "https://www.instagram.com/ecopower_saoroquesp?igsh=MTl4ZmJyNmt6Y2JxNg==",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Toritama",
    uf: "PE",
    phone: 81998215000,
    address: "Rua Joaquim Tabosa, 240, centro",
    facebook: "https://www.instagram.com/ecopowertoritama?igsh=MXI3ZXFxMjZnNTl5bA%3D%3D&utm_source=qr",
    instagram: "https://www.instagram.com/ecopowertoritama?igsh=MXI3ZXFxMjZnNTl5bA%3D%3D&utm_source=qr",
    photo: "7e7b704e-4083-4ff8-b71a-384c5f21b2d7_Agberto%20Albertino%20De.jpeg"
  },
  {
    municipio: "Jundiaí",
    uf: "SP",
    phone: "1197718-6363",
    address: "Em breve",
    facebook: "@ecopower_jundiaisp",
    instagram: "@ecopower_jundiaisp",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Nova viçosa posto da mata",
    uf: "BA",
    phone: 73999266796,
    address: "Rua João Durval Carneiro 721, centro posto da mata Ba",
    facebook: "A",
    instagram: "A",
    photo: "image_Julio%20Neto%20Dias%20Evan%201.jpg"
  },
  {
    municipio: "Ananindeua",
    uf: "PA",
    phone: 91983834747,
    address: "Passagem Jarbas Passarinho, 7 - Bairro do Atalaia - CEP 67.013-599",
    facebook: "https://www.instagram.com/fernandobraun_15?igsh=NGVhN2U2NjQ0Yg%3D%3D&utm_source=qr",
    instagram: "https://www.instagram.com/fernandobraun_15?igsh=NGVhN2U2NjQ0Yg%3D%3D&utm_source=qr",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "COLINA SP",
    uf: "SP",
    phone: 16982076403,
    address: "AV ANGELO MARTINS TRISTAO N 211 - CENTRO - COLINA SP",
    facebook: "",
    instagram: "",
    photo: "62e20dee-cba3-4908-8379-8ebed00734fb_Marcelo%20Polizelli%20No.jpg"
  },
  {
    municipio: "Barretos",
    uf: "SP",
    phone: "17 997870208",
    address: "Avenida quarenta e sete 423",
    facebook: "",
    instagram: "",
    photo: "1RHZag_iCphoD5XR6KxX5IBWzj7jxHr7t.png"
  },
  {
    municipio: "Teixeirade Freitas",
    uf: "BA",
    phone: "73-98848-8076",
    address: "Rua Massanore Nagao , 281, centro, shopping teixeira Mall",
    facebook: "https://www.facebook.com/ecopowertxf/",
    instagram: "@ecopower_teixeiradefreitas",
    photo: "WhatsApp%20Image%202024-04-25%20at%2016.55.49_Isaias%20Reis%20Barretos.jpeg"
  }
];
